## NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [ ]:
# NumPy array of one million integers
my_arr = np.arange(1_000_000)

In [ ]:
# NumPy array of a list of one million integers
my_list = list(range(1_000_000))

In [ ]:
# Timing the multiplication of the NumPy array by 2
%timeit my_arr2 = my_arr * 2

1.91 ms ± 23.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# Timing the multiplication of the list by 2
%timeit my_list2 = [x * 2 for x in my_list]

94.2 ms ± 4.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### The NumPy ndarray: A Multidimensional Array Object

In [6]:
# how NumPy enables batch computations with similar syntax to scalar values on built-in Python objects
import numpy as np

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]]) 

In [8]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
# Mathematical operations with data
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [10]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [11]:
# Shape of an array
data.shape

(2, 3)

In [12]:
# The data type of the array
data.dtype

dtype('float64')

#### Creating ndarrays

#####
The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data.

In [18]:
# a list is a good candidate for conversion
data1 = [6, 7.5, 8, 0, 1]

In [19]:
arr1 = np.array(data1)

In [20]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
# Nested sequences, like a list of lists, will result in a multidimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 

In [ ]:
arr2 = np.array(data2) # has two dimensions

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Inspecting the ndim and shape attributes of the array
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [ ]:
# The data type is stored in a special dtype metadata object unless specified numpy.array tries to infer the data type
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.empty((2, 3, 2))

array([[[1.10620883e-311, 2.86558075e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.37961302e-306, 8.60952352e-072]],

       [[4.46727880e-090, 6.81898836e-038],
        [3.55002444e-062, 1.32413208e-071],
        [6.48224660e+170, 5.82471487e+257]]])

In [35]:
# numpy.arange function creates evenly spaced values within a given interval
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Data Types for ndarrays

In [36]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [37]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [ ]:
# Converting or casting an array from one dtype to another using ndarray's astype method
arr = np.array([1, 2, 3, 4, 5])

In [43]:
arr.dtype

dtype('int32')

In [47]:
# integers are cast to floating-point numbers
float_arr = arr.astype(np.float64)

In [45]:
float_arr

array([1., 2., 3., 4., 5.])

In [46]:
float_arr.dtype

dtype('float64')

In [48]:
# if you cast some floating-point numbers to be of integer data type, the decimal part will be truncated
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [49]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [50]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [51]:
# using astype to convert an array of strings to a numeric type
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [52]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
#
int_array = np.arange(10)

In [54]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [55]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# 
zeros_uint32 = np.zeros(8, dtype="u4")

In [57]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

#### Arithmetic with NumPy Arrays

In [ ]:
# Arrays are important because they enable you to express batch operations on data without writing any for loops
# Any arithmetic operations between equal-size arrays apply the operation element-wise
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [59]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [65]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [64]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
# Comparisons between arrays of the same size yield Boolean arrays
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [69]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [70]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

##### 
Broadcasting is evaluating operations between differently sized arrays.

#### Basic Indexing and Slicing

In [ ]:
# One-dimensional arrays are simple;and are like lists, but with a fixed data type
arr = np.arange(10)

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[5]

5

In [74]:
arr[5:8]

array([5, 6, 7])

In [75]:
arr[5:8] = 12

In [76]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [77]:
# slice array
arr_slice = arr[5:8]

In [79]:
arr_slice

array([12, 12, 12])

In [80]:
# Reflection of the original array when values are modified
arr_slice[1] = 12345

In [81]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [82]:
# The “bare” slice [:] will assign to all values in an array
arr_slice[:] = 64

In [83]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [84]:
# In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [85]:
arr2d[2]

array([7, 8, 9])

In [ ]:
# 
arr2d[0][2]

3

In [87]:
arr2d[0, 2]

3

In [90]:
# 
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [91]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
# arr3d[0] is a 2 × 3 array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
# Both scalar values and arrays can be assigned to arr3d[0]
old_values = arr3d[0].copy()

In [94]:
arr3d[0] = 42

In [95]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3d[0] = old_values

In [97]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [98]:
# arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a one-dimensional array
arr3d[1, 0]

array([7, 8, 9])

In [ ]:
# same as the above as though we had indexed in two steps
x = arr3d[1]

In [100]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [101]:
x[0]

array([7, 8, 9])

##### Indexing with Slices

In [103]:
# Like one-dimensional objects, darrays can be sliced with the familiar syntax
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [104]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
# two-dimensional array
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# 
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [110]:
# selecting the second row but only the first two columns
low_dim_slice = arr2d[1, :2]

In [111]:
# lower_dim_slice is one-dimensional, and its shape is a tuple with one axis siz
low_dim_slice.shape

(2,)

In [112]:
# selecting the third column but only the first two rows
arr2d[:2, 2]

array([3, 6])

In [113]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [114]:
# assigning to a slice expression assigns to the whole selection
arr2d[:2, 1:] = 0

In [115]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### Boolean Indexing

In [116]:
# an example where we have some data in an array and an array of names with duplicates
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [117]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [118]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [119]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [122]:
# comparing names with the string "Bob" yields a Boolean array
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [121]:
# This Boolean array above can be passed when indexing the array
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [123]:
# The Boolean array must be of the same length as the array axis it’s indexing. You can even mix and match 
# Boolean arrays with slices or integers (or sequences of integers)


# examples, I selected from the rows where names == "Bob" and index the columns, too
data[names == "Bob", 1:]

array([[7],
       [0]])

In [124]:
data[names == "Bob", 1]

array([7, 0])

In [126]:
# To select everything but "Bob" you can either use != or negate the condition using ~
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [127]:
~(names == "Bob") 

array([False,  True,  True, False,  True,  True,  True])

In [128]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [129]:
# The ~ operator can be useful when you want to invert a Boolean array referenced by a variable
cond = names == "Bob"

In [130]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [131]:
# To select two of the three names to combine multiple Boolean conditions, use Boolean arithmetic operators like & (and) and | (or)
mask = (names == "Bob") | (names == "Will")

In [132]:
mask

array([ True, False,  True,  True,  True, False, False])

In [133]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])